/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_openquantumsafe_Rand */

#ifndef _RAND_H_INCLUDED_
#define _RAND_H_INCLUDED_
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_openquantumsafe_Rand
 * Method:    randombytes
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_net_ivpn_liboqs_Rand_randombytes
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_openquantumsafe_Rand
 * Method:    randombytes_switch_algorithm_native
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_net_ivpn_liboqs_Rand_randombytes_1switch_1algorithm_1native
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_openquantumsafe_Rand
 * Method:    randombytes_nist_kat_init
 * Signature: ([B[BJ)V
 */
JNIEXPORT void JNICALL Java_net_ivpn_liboqs_Rand_randombytes_1nist_1kat_1init
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jlong);

#ifdef __cplusplus
}
#endif
#endif
